name: Test

on:
  workflow_dispatch: # マニュアル実行

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3 # リポジトリをチェックアウトする
      - uses: mlugg/setup-zig@v1 # Zig をセットアップする
        with:
          version: 0.13.0
      - name: Test zig
        run: zig build test-zig
      - name: Test
        run: zig build test
